### ISSUE TITLE
[DOCS - Refactor] port technical documentation from community.optimism.io

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/docs#42]
Port all existing documentation into the new repository:

- [x] biz ethereum-optimism/developer-support#97 
- [x] developers ethereum-optimism/docs#41
- [x] guides ethereum-optimism/developer-support#101
- [x] identity ethereum-optimism/developer-support#102
- [x] protocol ethereum-optimism/developer-support#103
- [x] sdk ethereum-optimism/developer-support#104
- [x] security-model ethereum-optimism/developer-support#105
- [x] useful-tools ethereum-optimism/developer-support#160 

**Additional context**

While moving documentation over to the new repository, we should perform QA, and update outdated information.

Details about any changes made during the content migration can be found in this [google sheet](https://docs.google.com/spreadsheets/d/1olEE33aRFStTmhOoAGwuvpjxSvRav0ArFqxcd_lM13s/edit?usp=sharing)
