### ISSUE TITLE
[DOCS] Add meta content for pages

### ISSUE THREAD

**Issue by cpengilly** [ethereum-optimism/docs#60]
- [x] add meta page title @ top of each page
- [x] add meta language @ top of each page
- [x] add meta description @ top of each page

description Should be 2-3 sentences long. 

---
title: Supercharge Your DApp with Account Abstraction
lang: en-US
description: This guide explains how account abstraction enables users to utilize smart contracts to build, onboard, and scale dapps.
---
